#! /bin/csh -f

# compute clutter, load up file
#
# Usage: compute_clutter start_yyyy mm dd hh mm ss end_yyyy mm dd hh mm ss

cd ~/projDir/ingest/params

MdvMedian -params MdvMedian.cart -start "$argv[1] $argv[2] $argv[3] $argv[4] $argv[5] $argv[6]" -end "$argv[7] $argv[8] $argv[9] $argv[10] $argv[11] $argv[12]" -debug


