#!/usr/bin/perl
#
# DO NOT EDIT THIS FILE
#
# put_new.plv
#

$ping_host = "www.wtwma.com";
$retry = 1;
while(system("/bin/ping -c1 $ping_host") && ($retry >= 0)){
   sleep 10;
   $retry--;
}

chop($ENV{'HOSTNAME'} = `/bin/hostname`);

print "Starting put script\n";

require '/home/titan/projDir/system/scripts/FTP.pm';

chop($day_dir = `/bin/date +%b-%d`);

$input_cappi = "/home/titan/projDir/output/cappi.xwd";

$filename_cappi = "/home/titan/projDir/output/cappi.gif";

# CHANGE********************************************
# NEXT LINE IS ORIGINAL FTP CAPPI LINE
#$filename_ftp_cappi =  'htdocs/archive/' . 'cappi-'.`find $input_cappi -printf %Cm%Cd%CH%CM` . ".gif";

$filename_ftp_latest = 'htdocs/sangelo/' . 'latest.gif';

while(`find /home/titan/projDir/output/cappi.xwd -size 0k`){
   sleep(10);
   print "Wait for new Cappi\n";
}

do {
print "Process new Cappi\n";
system("convert $input_cappi $filename_cappi");
print "FINISHED CAPPI GIF\n";
#system("convert $input_cappi  $filename_cappi");
} while(`find  $filename_cappi -size 0k`);

# CHANGE********************************************
$ftp = Net::FTP->new('www.wtwma.com');

if(!$ftp){
	die "Failed to connect: $_\n";
}

print "Starting FTP\n";

$ftp->debug(1);

print "Turned on debug\n";

# CHANGE********************************************
$ftp->login('wtwmaco%wtwma.com', 'cyhlmmJQ');

$ftp->binary;

$ftp->put($filename_cappi, $filename_ftp_latest);
#$ftp->put($filename_cappi, $filename_ftp_cappi);

unlink("$filename_cappi") || warn "Failed to unlink: $!\n";



