#! /bin/csh

source set_env_vars

cd $DATA_DIR

running "DsServerMgr"
if ($status == 1) then
    echo starting DsServerMgr
    DsServerMgr -debug -debug -instance primary -qmax -1 >& /dev/null &
endif

