#! /bin/csh

#
# Start virtual X server for Display :1000:0
#
# Choose a high display number so that the port does not
# conflict with an ssh session.

running "Xvfb :1000.0"
if ($status == 1) then
    Xvfb :1000.0 -screen 0 2000x2000x24 -pixdepths 24 -ld 100000 -ls 10000 |& \
	LogFilter -d $ERRORS_LOG_DIR -p Xvfb -i 1 >& /dev/null &
endif

# set the font path

setenv DISPLAY :1000.0
set_font_path >& /dev/null
xrdb -display $DISPLAY $PROJ_DIR/display/params/XResources4CIDD
