#####################################333####
# .cshrc file for TITAN LROSE NEXRAD project
############################################

if ( $?prompt ) then
  set prompt = "`hostname`:\!>"
  set autoexpand
  set autolist
  set cdpath = ( ~ )
  set pushdtohome
endif

unset autologout
set autologout=0

umask 002
setenv TAPE /dev/st0
setenv PRINTER nwcolor

# Set the build environment

setenv LANG C

# Note: options for HOST_OS environment variable are
#  LINUX_LROSE
#  LINUX_OSX

setenv HOST_OS LINUX_LROSE

setenv LROSE_CORE_DIR $HOME/git/lrose-core
setenv LROSE_INSTALL_DIR /usr/local/lrose

setenv RAP_MAKE_INC_DIR $LROSE_CORE_DIR/codebase/make_include
setenv RAP_MAKE_BIN_DIR $LROSE_CORE_DIR/codebase/make_bin

setenv RAP_INC_DIR $LROSE_INSTALL_DIR/include
setenv RAP_LIB_DIR $LROSE_INSTALL_DIR/lib
setenv RAP_BIN_DIR $LROSE_INSTALL_DIR/bin
setenv RAP_MAN_DIR $LROSE_INSTALL_DIR/man
setenv RAP_DOC_DIR $LROSE_INSTALL_DIR/doc

setenv RAP_SHARED_INC_DIR $RAP_INC_DIR
setenv RAP_SHARED_LIB_DIR $RAP_LIB_DIR
setenv RAP_SHARED_BIN_DIR $RAP_BIN_DIR

# --- OTHER BUILD SETTINGS

setenv QTDIR /usr/lib64/qt5
setenv FC gfortran
setenv GCC_WARNINGS -Wall

# --- LD library path --

setenv LD_LIBRARY_PATH $QTDIR/lib:/usr/local/lib:$LROSE_INSTALL_DIR/lib

# --- NCAR GRAPHICS ---

setenv NCARG_ROOT /usr/local/ncarg

# --- JAVA ---

setenv JAVA_HOME /usr/java/latest
setenv ANT_HOME /usr/local/ant
setenv RAP_JAR_DIR $LROSE_INSTALL_DIR/java/dist/lib

# --- RUNTIME ---

setenv PROJ_DIR $HOME/projDir
setenv TITAN_HOME $PROJ_DIR

setenv DATA_HOST localhost
setenv DATA_DIR $PROJ_DIR/data
setenv RAP_DATA_DIR $DATA_DIR

setenv TMP_DIR $DATA_DIR/tmp

setenv LOG_DIR $DATA_DIR/logs
setenv DATA_DISTRIB_LOG_DIR $LOG_DIR/distrib
setenv ERRORS_LOG_DIR $LOG_DIR/errors
setenv RESTART_LOG_DIR $LOG_DIR/restart

setenv PROCMAP_HOST localhost
setenv DATA_MAPPER_ACTIVE true
setenv LDATA_FMQ_ACTIVE true

setenv DS_COMM_TIMEOUT_MSECS 60000
setenv DS_PING_TIMEOUT_MSECS 20000

setenv MDV_WRITE_FORMAT FORMAT_MDV
setenv MDV_WRITE_USING_EXTENDED_PATHS TRUE
setenv MDV2NETCDF_WRITE_LATLON_ARRAYS FALSE

# --- project info --- 

if (-f $PROJ_DIR/system/params/project_info) then
  source $PROJ_DIR/system/params/project_info
endif

# python

setenv PYTHONPATH ~/anaconda2/pkgs

# --- Path ---

# Assemble path to include all scripts directories
# then install dir, then the rest

set path = (.)

if ( -d $PROJ_DIR ) then
  foreach dir ($PROJ_DIR/*)
    if (-d $dir/scripts) then
      set path = ($path $dir/scripts)
    endif
  end
endif

set path = ($path $LROSE_INSTALL_DIR/bin)  
set path = ($path $PROJ_DIR/dial/Matlab)
set path = ($path $HOME/cidd/bin)

set path = ($path $HOME/git/lrose-core/codebase/apps/scripts/src)  
set path = ($path $HOME/git/lrose-core/codebase/apps/procmap/src/scripts)  

set path = ($path ~/bin $QTDIR/bin \
        ~/anaconda2/bin \
	$JAVA_HOME/bin $ANT_HOME/bin \
	/usr/local/bin /usr/local/sbin /usr/bin/X11 \
        /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin \
	/opt/gfortran/irun/bin /opt/spol/bin /opt/local/lrose/bin \
        /usr/sigmet/bin /usr/sigmet/bin/rda $QTDIR/bin )

# history

set savehist=0

# --- Aliases ---

if ($?prompt) then

  alias sc source ~/.cshrc

  alias setprompt 'set prompt="(`hostname`) `basename $cwd` ! % "'
  alias cd 'cd \!*;setprompt; echo $cwd'
  alias push 'pushd \!*; cd .'
  alias pop 'popd; cd .'

  set prompt = "%m:%~%# "             # tcsh
  set showdots                        # tcsh
  set watch = (1 root any)            # tcsh
  set history=1000
  set nobeep
  set time = 5

  setenv EDITOR emacs
  setenv PAGER less
  setenv LESS "-cMe"
  setenv LESSOPEN "|lesspipe.sh %s"
  setenv LESSCHARSET latin1

  alias h history
  alias ssh 'ssh -X'

  alias rm 'rm -i'
  alias mv 'mv -i'
  alias cp 'cp -i' 

  alias df 'df -h'
  set filec
  set fignore = (.o .ln)

  alias catw 'cat `which \!*`'
  alias lessw 'less `which \!*`'
  alias emacsw 'emacs -nw `which \!*`'
  alias viw 'vi `which \!*`'

  alias lst 'ls -l \!* | awk \{s+=\$4\}END\{print\ s\}'
  alias la 'ls -la --color=tty'
  alias ll 'ls -l --color=tty'
  alias lt 'ls -lt --color=tty'
  alias lat 'ls -alt --color=tty'
  alias l 'ls -sF'
  alias L ls -agl
  alias LS ls -aFRts 

  alias xx 'xrdb ~/.Xdefaults'
  alias cvs 'cvs -d :pserver:${CVSUSER}@localhost:/cvs \!*'
  alias cvsforward 'ssh -a -x -C -Y -R 2401:localhost:2401 -R 8888:localhost:8888'
  alias cvsin 'ssh -a -x -C -L 2401:cvs:2401'
  alias cvsout 'ssh -a -x -C -R 2401:cvs:2401'
  
  alias gstat 'git status'
  alias gcom 'git commit -am \!*'
  alias gpush 'git push'
  alias gpull 'git pull'
  alias gdiff 'git diff '
  alias gdt 'git difftool -g -y -t tkdiff '

  alias psg 'ps axww | sed -n "1p; \|sed .*/\!*/|d; /\!*/p"'
  alias pslg 'ps alxww | sed -n "1p; \|sed .*/\!*/|d; /\!*/p"'
  alias psug 'ps auxww | sed -n "1p; \|sed .*/\!*/|d; /\!*/p"'
  alias psx 'ps xww | grep -v LogFilter'
  alias ensc 'enscript -2r -fCourier7'

  alias print_procmap 'print_procmap -hb -up -status'
  alias PrintDataMap 'PrintDataMap -all -relt -lreg'
  alias ppm 'print_procmap -hb -up -status'
  alias pdm 'PrintDataMap -all -relt -lreg'
  alias pdmp 'PrintDataMap -all -relt -lreg -c 5 | egrep "pecan|DataType" '
  alias dmd 'DataMapper -delete '
  alias pcheck 'procmap_list_check -proc_list $PROJ_DIR/control/proc_list'
  alias dcheck 'DataMapper_list_check -data_list $PROJ_DIR/control/data_list'
  alias pcheckOK 'pcheck -ok'
  alias dcheckOK 'dcheck -ok'
  alias ph 'get_host_type'

# save to dvd

  alias savedvd 'growisofs -Z /dev/dvd -r -J'
  alias saveiso2dvd 'growisofs -dvd-compat -Z /dev/dvd='

#    eval `dircolors ~/.dircolors`      # Set up color-ls variables.

  setprompt

endif

