#! /bin/csh -f

#
# usage: delete_titan_data yes PLEASE I REALLY want to do this
#

if ($1 != yes || $2 != PLEASE || $3 != I || $4 != REALLY || \
    $5 != want || $6 != to || $7 != do || $8 != this) then
    echo Incorrect command line syntax
    echo \!\!\!\!\! WARNING - you will remove all titan data with this command \!\!\!\!\!
    echo
    echo Usage: delete_titan_data yes PLEASE I REALLY want to do this
    echo
    exit -1
endif

/bin/rm -rf $DATA_DIR/mdv/radar
/bin/rm -rf $DATA_DIR/mdv/precip
/bin/rm -rf $DATA_DIR/mdv/vil
/bin/rm -rf $DATA_DIR/spdb/ac_posn
/bin/rm -rf $DATA_DIR/spdb/ascii_ac_posn
/bin/rm -rf $DATA_DIR/spdb/tstorms
/bin/rm -rf $DATA_DIR/titan/storms
/bin/rm -rf $PROJ_DIR/logs/*










