#!/bin/csh -f
# kills all processes that may be running
# 

procmap_list_kill -proc_list ~/projDir/control/proc_list -fast -debug

killall java
killall Xvfb

killall DsServerMgr
killall Janitor
killall Scout
killall DataMapper
killall RadxConvert
killall Radx2Grid
killall EsdAcIngest
killall Titan
killall PrecipAccum
killall Mdv2Vil
killall Tstorms2Spdb
killall Rview
killall TimeHist
killall CIDD

killall MdvMerge2
killall GetAwsRadar.py

killall procmap

# kills all processes that may be running on an AOAWS machine 
# 
# This is done by running killall on all executable files in
# ~/projDir/bin
#

foreach dir ($LROSE_INSTALL_DIR/bin*)
  if (-d $dir) then
    cd $dir
    foreach file (*)
      if (-f $file && -x $file) then
#      pkill $file >& /dev/null
       killall -q $file >& /dev/null
      endif
    end
  endif
end

