#!/bin/csh -f
# kills all processes that may be running
# 

pkill java
pkill Xvfb

pkill DsServerMgr
pkill Janitor
pkill Scout
pkill DataMapper
pkill RadxConvert
pkill Radx2Grid
pkill EsdAcIngest
pkill Titan
pkill PrecipAccum
pkill Mdv2Vil
pkill Tstorms2Spdb
pkill Rview
pkill TimeHist
pkill CIDD

pkill MdvMerge2
pkill GetAwsRadar.py

pkill procmap

# kills all processes that may be running on an AOAWS machine 
# 
# This is done by running killall on all executable files in
# ~/projDir/bin
#

foreach dir ($LROSE_INSTALL_DIR/bin*)
  if (-d $dir) then
    cd $dir
    foreach file (*)
      if (-f $file && -x $file) then
#      pkill $file >& /dev/null
       killall -q $file >& /dev/null
      endif
    end
  endif
end

