#! /bin/csh

cd $RAP_DATA_DIR

running "DsServerMgr"
if ($status == 1) then
    nice DsServerMgr -instance primary -qmax -1 |& \
	LogFilter -d $ERRORS_LOG_DIR -p DsServerMgr -i primary >& /dev/null &
endif

