#! /bin/csh
#

#
# start auto_restart only if cron is active
#

set checkfile=/tmp/croncheck_auto_restart
crontab -l >& $checkfile
grep "no crontab" $checkfile >& /dev/null

# if grep returns 1, cron is there so go ahead

if ($status == 1) then
    start_auto_restart
endif

# rm tmp file

/bin/rm -f $checkfile



